version: '3.7'

services:
    db:
        image: mongo
        container_name: db
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - mongo_data:/data/db
        ports:
            - '27017:27017'
        command: mongod --logpath=/dev/null # --quiet

volumes:
  mongo_data:
